### ISSUE TITLE
Weird support for app router

### ISSUE THREAD

**Issue by nrmnqdds** [triyanox/next-routes#6]
idk if i do this wrong. I'm using app dir and it forces me to use href like `app/auth/login` instead of `/auth/login`

`next.config.mjs`
![image](https://github.com/triyanox/next-routes/assets/65181897/5136b130-de63-4de0-ad92-d690c88682e7)

`lib/link$.ts`
![image](https://github.com/triyanox/next-routes/assets/65181897/4d7cf342-c09e-43f7-8fc5-384008b92ea8)

**Comment by chaqchase** [comment]
Hey @nrmnqdds I understand what the issue is! because they maybe different setups of your routes location, whether you're using the `src` directory or not; you have the ability to use the advanced setup, but the thing you have to keep in mind is the path to the `app` dir is relative to the root

So you have to do something like this something like this

```ts
import withRoutes from '@triyanox/next-routes';
import path from 'path';

const config = withRoutes(
  {
    //... your next config
  },
  {
    appDir: path.resolve(process.cwd(), 'app'), // optional: The path to your Next.js app directory. Defaults to "src/app".
    utilsPath: path.resolve(process.cwd(), 'lib/link$.ts'), // optional: The path where the plugin will generate utility functions. Defaults to "src/lib/link$.ts".
  },
);

export default config;
```

Let me know if this solved the issue ! And thanks again @nrmnqdds for opening this issue !
